-- Schema real do MySQL remoto (induscolor_sistema), conferido via DESCRIBE.
-- Este arquivo NÃO é executado pela aplicação — serve apenas de documentação
-- para manter as queries do backend em sync com as colunas reais.

-- rh_vagas
--   id INT PK AUTO_INCREMENT
--   titulo VARCHAR(150) NOT NULL
--   slug VARCHAR(180) NOT NULL UNIQUE
--   descricao MEDIUMTEXT
--   requisitos MEDIUMTEXT
--   beneficios MEDIUMTEXT
--   setor VARCHAR(100)
--   tipo_contrato VARCHAR(80)
--   localizacao VARCHAR(120)
--   status ENUM('aberta','pausada','fechada') DEFAULT 'aberta'
--   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
--   updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

-- rh_candidatos
--   id INT PK AUTO_INCREMENT
--   nome VARCHAR(150) NOT NULL
--   email VARCHAR(150)
--   telefone VARCHAR(50)
--   cidade VARCHAR(100)
--   linkedin VARCHAR(255)
--   curriculo_url MEDIUMTEXT
--   observacoes MEDIUMTEXT
--   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
--   updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

-- rh_candidaturas
--   id INT PK AUTO_INCREMENT
--   candidato_id INT NOT NULL (FK -> rh_candidatos.id)
--   vaga_id INT NULL (FK -> rh_vagas.id; NULL = banco de talentos)
--   origem VARCHAR(80) DEFAULT 'site_induscolor'
--   etapa ENUM('novo_curriculo','triagem','entrevista','teste','aprovado','reprovado','banco_talentos') DEFAULT 'novo_curriculo'
--   status VARCHAR(80) DEFAULT 'em_analise'
--   avaliacao_rh MEDIUMTEXT
--   pretensao_salarial DECIMAL(10,2)
--   disponibilidade VARCHAR(120)
--   observacoes MEDIUMTEXT
--   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
--   updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

-- rh_entrevistas
--   id INT PK AUTO_INCREMENT
--   candidatura_id INT NOT NULL (FK -> rh_candidaturas.id)
--   data_entrevista DATETIME
--   entrevistador VARCHAR(150)
--   tipo VARCHAR(80)
--   parecer MEDIUMTEXT
--   nota_comportamental DECIMAL(4,2)
--   nota_tecnica DECIMAL(4,2)
--   status ENUM('agendada','realizada','cancelada') DEFAULT 'agendada'
--   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
--   updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

-- rh_historico
--   id INT PK AUTO_INCREMENT
--   candidatura_id INT NOT NULL (FK -> rh_candidaturas.id)
--   acao VARCHAR(120) NOT NULL
--   etapa_anterior VARCHAR(80)
--   etapa_nova VARCHAR(80)
--   observacao MEDIUMTEXT
--   usuario VARCHAR(150)
--   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
